<?php $this->placeholder('content')->captureStart(); ?>
<?php /* @var $form \Admin\Form\User\ChangePassword */ ?>
<?php /* @var $action string */ ?>
<div class="well well-message">
    <?php $form->setAttribute('action', $this->url('user', array('action' => 'changePassword'))); ?>
    <?php echo $this->form()->openTag($this->ztbFormPrepare($form, 'horizontal')); ?>
    <?php if ($action === 'change'): ?>
        <h3 class="entity-title"><?php echo $this->escapeHtml($this->translate("Change Password")); ?></h3>

        <?php if (count($form->getExceptionMessages()) > 0): ?>
            <div class="alert alert-error">
                <b><?php echo $this->escapeHtml($this->translate("Exceptions")); ?>:</b><br/>
                <ul class="alert-block alert-warning">
                    <?php foreach ($form->getExceptionMessages() as $message): ?>
                        <li><?php echo $this->escapeHtml($message); ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
        <?php foreach ($form->getMessages() as $key => $messages): ?>
            <div class="alert alert-error">
                <b><?php echo $this->escapeHtml($this->translate($form->get($key)->getLabel())); ?>:</b><br/>
                <ul class="alert-block alert-warning">
                    <?php foreach ($messages as $message): ?>
                        <li><?php echo $this->escapeHtml($message); ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endforeach; ?>

        <div class="control-group">
            <?php echo $this->formLabel($form->get('oldPassword')); ?>
            <div class="controls">
                <?php echo $this->formInput($form->get('oldPassword')->setAttribute('class', 'input-xlarge')); ?>
            </div>
        </div>
        <div class="control-group">
            <?php echo $this->formLabel($form->get('newPassword')); ?>
            <div class="controls">
                <?php echo $this->formInput($form->get('newPassword')->setAttribute('class', 'input-xlarge')); ?>
            </div>
        </div>
        <div class="control-group">
            <?php echo $this->formLabel($form->get('confirmPassword')); ?>
            <div class="controls">
                <?php echo $this->formInput($form->get('confirmPassword')->setAttribute('class', 'input-xlarge')); ?>
            </div>
        </div>
        <div class="form-actions">
            <?php echo $this->ztbFormButton($form->get('submitButton'), null, array('btn_type' => 'warning')); ?>
            &nbsp;
            <?php echo $this->ztbFormButton($form->get('cancel')->setAttribute('class', 'input-small')); ?>
            &nbsp;
        </div>
    <?php else: ?>
        <h3 class="entity-title"><?php echo $this->escapeHtml($this->translate("Password changed")); ?></h3>
        <p><?php
            echo $this->escapeHtml($this->translate("Password has been succefully changed!"));
            ?></p>
        <div class="form-actions">
            <?php
            echo $this->ztbFormButton($form->get('cancel')->setAttribute('class', 'pull-right input-medium')
                            ->setAttribute('formaction', $this->url('user', array('action' => 'detailProfile'))), 'Back to Profile', array('icon' => 'arrow-left'));
            ?>
        </div>
    <?php endif; ?>

    <?php $this->form()->closeTag(); ?>
</div>
<?php $this->placeholder('content')->captureEnd(); ?>
<?php echo /* $this->stripContent */ ($this->placeholder('content')); ?>