<?php $this->placeholder('content')->captureStart(); ?>
<?php /* @var $users \Zend\Paginator\Paginator */ ?>
<?php /* @var $this \Zend\View\Renderer\PhpRenderer */ ?>
<form method="post">
    <?php echo $this->formHidden((new \Zend\Form\Element\Hidden('returnTo'))->setValue($this->url('userList', array('action' => 'index', 'page' => $users->getCurrentPageNumber())))); ?>
    <div class="btn-group">
        <button class="btn btn-info" title="<?php echo $this->escapeHtml($this->translate('Detail user')) ?>"   type="submit" formaction="<?php echo $this->url('user', array('action' => 'detail')); ?>"><span class="icon icon-book icon-white"></span> <?php echo $this->escapeHtml($this->translate("Detail")); ?></button>
        <button class="btn btn-warning" title="<?php echo $this->escapeHtml($this->translate('Alter user')) ?>" type="submit" formaction="<?php echo $this->url('user', array('action' => 'update')); ?>"><span class="icon icon-edit icon-white"></span> <?php echo $this->escapeHtml($this->translate("Alter")); ?></button>
        <button class="btn btn-danger" title="<?php echo $this->escapeHtml($this->translate('Remove user')) ?>" type="submit" formaction="<?php echo $this->url('user', array('action' => 'remove')); ?>"><span class="icon icon-remove icon-white"></span> <?php echo $this->escapeHtml($this->translate("Remove")); ?></button>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th />
                <th><?php echo $this->escapeHtml($this->translate('Name')); ?></th>
                <th><?php echo $this->escapeHtml($this->translate('User')); ?></th>
                <th><?php echo $this->escapeHtml($this->translate('Active')); ?></th>
                <th><?php echo $this->escapeHtml($this->translate('Date Creation')); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $user): ?>
                <?php /* @var $user \Admin\Model\Entity\User */ ?>
                <tr>
                    <td><input type="radio" name="id" value="<?php echo $this->escapeHtml($user->getId()); ?>" /></td>
                    <td><?php echo $this->escapeHtml($user->getName()); ?></td>
                    <td><?php echo $this->escapeHtml($user->getUsername()); ?></td>
                    <td>
                        <?php if ($user->isActive()): ?>
                            <button class="btn btn-mini btn-success" title="<?php echo $this->escapeHtml($this->translate('Lock user')); ?>"   formaction="<?php echo $this->url('user', array('action' => 'lock', 'id' => $user->getId())); ?>"><span class="icon icon-eye-open icon-white"></span></button>
                        <?php else: ?>
                            <button class="btn btn-mini btn-inverse" title="<?php echo $this->escapeHtml($this->translate('Unlock user')); ?>" formaction="<?php echo $this->url('user', array('action' => 'unlock', 'id' => $user->getId())); ?>"><span class="icon icon-eye-close icon-white"></span></button>
                            <?php endif; ?>
                    </td>
                    <td><?php echo $this->dateFormat($user->getDateCreation(), IntlDateFormatter::MEDIUM); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($users, 'Sliding', 'partial/paginatorControl.phtml', array('route' => 'userList')); ?>
</form>
<?php $this->placeholder('content')->captureEnd(); ?>
<?php echo $this->stripContent($this->placeholder('content')); ?>