<?php $this->placeholder('content')->captureStart(); ?>
<?php /* @var $users \Zend\Paginator\Paginator */ ?>
<?php /* @var $this \Zend\View\Renderer\PhpRenderer */ ?>
<form id="<?php echo "userlist_" . time(); ?>" method="post">
    <?php echo $this->formHidden((new \Zend\Form\Element\Hidden('returnTo'))->setValue($this->url('userList', array('action' => 'index', 'page' => $users->getCurrentPageNumber())))); ?>
    <h3 class="entity-title">
        <?php echo $this->escapeHtml($this->translate('Users')); ?>
        <div class="pull-right"><?php echo $this->paginationControl($users, 'Sliding', 'partial/paginatorControl.phtml', array('route' => 'userList')); ?></div>
    </h3>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th />
                <th><?php echo $this->escapeHtml($this->translate('Name')); ?></th>
                <th><?php echo $this->escapeHtml($this->translate('User')); ?></th>
                <th><?php echo $this->escapeHtml($this->translate('Active')); ?></th>
                <th><?php echo $this->escapeHtml($this->translate('Date Creation')); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $user): ?>
                <?php /* @var $user \Admin\Model\Entity\User */ ?>
                <tr>
                    <td><input type="radio" name="id" value="<?php echo $this->escapeHtml($user->getId()); ?>" /></td>
                    <td><?php echo $this->escapeHtml($user->getName()); ?></td>
                    <td><?php echo $this->escapeHtml($user->getUsername()); ?></td>
                    <td>
                        <?php if ($user->isActive()): ?>
                            <button class="btn btn-mini btn-success" title="<?php echo $this->escapeHtml($this->translate('Lock user')); ?>"   formaction="<?php echo $this->url('user', array('action' => 'lock', 'id' => $user->getId())); ?>"><span class="icon icon-eye-open icon-white"></span></button>
                        <?php else: ?>
                            <button class="btn btn-mini btn-inverse" title="<?php echo $this->escapeHtml($this->translate('Unlock user')); ?>" formaction="<?php echo $this->url('user', array('action' => 'unlock', 'id' => $user->getId())); ?>"><span class="icon icon-eye-close icon-white"></span></button>
                        <?php endif; ?>
                    </td>
                    <td><?php echo $this->dateFormat($user->getDateCreation(), IntlDateFormatter::MEDIUM); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="form-actions">
        <button class="btn btn-info"    type="submit" formaction="<?php echo $this->url('user', array('action' => 'detail')); ?>">
            <span class="icon icon-white icon-book"></span>
            <?php echo $this->escapeHtml($this->translate("Detail")); ?>
        </button>
        <button class="btn btn-warning" type="submit" formaction="<?php echo $this->url('user', array('action' => 'update')); ?>">
            <span class="icon icon-white icon-edit"></span>   
            <?php echo $this->escapeHtml($this->translate("Alter")); ?>
        </button>
        <button class="btn btn-warning" type="submit" formaction="<?php echo $this->url('user', array('action' => 'alterPassword')); ?>">
            <span class="icon icon-white icon-lock"></span>   
            <?php echo $this->escapeHtml($this->translate('Reset password')) ?>
        </button>
        <button class="btn btn-danger"  type="submit" formaction="<?php echo $this->url('user', array('action' => 'remove')); ?>">       
            <span class="icon icon-white icon-remove"></span> 
            <?php echo $this->escapeHtml($this->translate("Remove")); ?>
        </button>
    </div>
</form>
<?php $this->placeholder('content')->captureEnd(); ?>
<?php echo $this->stripContent($this->placeholder('content')); ?>