<?php $this->placeholder('content')->captureStart(); ?>
<?php /* @var $users \Zend\Paginator\Paginator */ ?>
<?php /* @var $this \Zend\View\Renderer\PhpRenderer */ ?>
<form id="<?php echo "userlist_" . time(); ?>" method="post">
    <?php echo $this->formHidden((new \Zend\Form\Element\Hidden('returnTo'))->setValue($this->url('userList', array('action' => 'index', 'page' => $users->getCurrentPageNumber())))); ?>
    <h3 class="entity-title">
        <?php echo $this->escapeHtml($this->translate('Users')); ?>
        <div class="pull-right"><?php echo $this->paginationControl($users, 'Sliding', 'partial/paginatorControl.phtml', array('route' => 'userList')); ?></div>
    </h3>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th />
                <th><?php echo $this->escapeHtml($this->translate('Name')); ?></th>
                <th><?php echo $this->escapeHtml($this->translate('User')); ?></th>
                <th><?php echo $this->escapeHtml($this->translate('Active')); ?></th>
                <th><?php echo $this->escapeHtml($this->translate('Date Creation')); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $user): ?><?php /* @var $user \Admin\Model\Entity\User */ ?>
                <tr>
                    <td><input type="radio" name="id" value="<?php echo $this->escapeHtml($user->getId()); ?>" /></td>
                    <td><?php echo $this->escapeHtml($user->getName()); ?></td>
                    <td><?php echo $this->escapeHtml($user->getUsername()); ?></td>
                    <td>
                        <?php if ($user->isActive()): ?>
                            <button class="btn btn-mini btn-success" title="<?php echo $this->escapeHtml($this->translate('Lock user')); ?>"   formaction="<?php echo $this->url('user', array('action' => 'lock', 'id' => $user->getId())); ?>"><span class="icon icon-eye-open icon-white"></span></button>
                        <?php else: ?>
                            <button class="btn btn-mini btn-inverse" title="<?php echo $this->escapeHtml($this->translate('Unlock user')); ?>" formaction="<?php echo $this->url('user', array('action' => 'unlock', 'id' => $user->getId())); ?>"><span class="icon icon-eye-close icon-white"></span></button>
                        <?php endif; ?>
                    </td>
                    <td><?php echo $this->dateFormat($user->getDateCreation(), IntlDateFormatter::MEDIUM); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="form-actions">
        <?php
        echo $this->ztbFormButton((new \Zend\Form\Element\Button('btn_create_' . time(), array('icon' => 'plus',)))->setAttributes(array(
                    'type' => 'submit',
                    'formaction' => $this->url('user', array('action' => 'create')),
                    'class' => 'input-medium',
                )), 'Create');
        ?>
        &nbsp;
        <?php
        echo $this->ztbFormButton((new \Zend\Form\Element\Button('btn_detail_' . time(), array('icon' => 'book',)))->setAttributes(array(
                    'type' => 'submit',
                    'formaction' => $this->url('user', array('action' => 'detail')),
                    'class' => 'input-medium',
                )), 'Detail');
        ?>
        &nbsp;
        <?php
        echo $this->ztbFormButton((new \Zend\Form\Element\Button('btn_edit_' . time(), array('icon' => 'edit',)))->setAttributes(array(
                    'type' => 'submit',
                    'formaction' => $this->url('user', array('action' => 'update')),
                    'class' => 'input-medium',
                )), 'Edit');
        ?>
        &nbsp;
        <?php
        echo $this->ztbFormButton((new \Zend\Form\Element\Button('btn_resetPassword_' . time(), array('icon' => 'lock',)))->setAttributes(array(
                    'type' => 'submit',
                    'formaction' => $this->url('user', array('action' => 'resetPassword')),
                    'class' => 'input-large',
                )), 'Reset Password');
        ?>
        &nbsp;
        <?php
        echo $this->ztbFormButton((new \Zend\Form\Element\Button('btn_remove_' . time(), array('icon' => 'remove',)))->setAttributes(array(
                    'type' => 'submit',
                    'formaction' => $this->url('user', array('action' => 'remove')),
                    'class' => 'input-medium',
                )), 'Remove');
        ?>
    </div>
</form>
<?php $this->placeholder('content')->captureEnd(); ?>
<?php echo $this->stripContent($this->placeholder('content')); ?>