<?php $this->placeholder('content')->captureStart(); ?>
<?php /* @var $form \Admin\Form\User\ChangePassword */ ?>
<?php /* @var $action string */ ?>
<?php $form->setAttribute('action', $this->url('user', array('action' => 'resetPassword', 'id' => $form->get('id')->getValue()))); ?>
<div class="well well-message">
    <?php echo $this->form()->openTag($this->ztbFormPrepare($form)); ?>
    <?php echo $this->formHidden((new \Zend\Form\Element\Hidden('returnTo'))->setValue($this->url('user', array('action' => 'detail', 'id' => $form->get('id')->getValue())))); ?>
    <?php echo $this->formHidden($form->get('id')); ?>
    <h4><?php echo $this->escapeHtml(sprintf($this->translate("Reset password of %s (%s)?"), $form->get('name')->getValue(), $form->get('username')->getValue())); ?></h4>
    <div class="form-actions">
        <?php echo $this->ztbFormButton($form->get('resetPassword'), null, array('btn_type' => 'warning')); ?>
        &nbsp;
        <?php echo $this->ztbFormButton($form->get('cancel')->setAttribute('class', 'pull-right input-medium')); ?>
        &nbsp;
    </div>
    <?php $this->form()->closeTag(); ?>
</div>
<?php $this->placeholder('content')->captureEnd(); ?>
<?php echo $this->stripContent($this->placeholder('content')); ?>

