<?php foreach ($categories as $cat): ?><?php /* @var $cat \Application\Model\Entity\Category */ ?>
    <tr meta-number="<?php echo $cat->getNumber(); ?>" 
        <?php if ($cat->getParent()) : ?>meta-parent-number="<?php echo $cat->getParent()->getNumber(); ?>"<?php endif; ?>>
        <td style="text-indent: <?php echo $level * 2; ?>ex">
            <input type="radio" name="number" value="<?php echo $cat->getNumber(); ?>" />
            <?php echo $this->escapeHtml($cat->getCode()); ?>
        </td>
        <td><?php echo $this->escapeHtml($cat->getDescription()); ?></td>
        <td><?php echo $this->escapeHtml($this->translate($cat->getFlowType() == 1 ? "Input" : "Output")); ?></td>
    </tr>
    <?php echo $this->partial('application/category/partial/category_tr.phtml', array('categories' => $cat->getChildren(), 'level' => ($level + 1))); ?>
<?php endforeach; ?>
