<?php if ($level === 0): ?>
    <option value="0"><?php echo $this->escapeHtml($this->translate(" -- None -- ")); ?></option>
<? endif; ?>
<?php foreach ($categories as $category): ?><?php /* @var $category \Application\Model\Entity\Category */ ?>
    <?php if ($category->getNumber() === null): ?>
        <?php continue; ?>
    <?php endif; ?>

    <option value="<?php echo $this->escapeHtml($category->getNumber()); ?>"
            <? if ($numberSelected == $category->getNumber()): ?>selected<? endif; ?>>
        <?php echo str_repeat('&nbsp;', $level * 2); ?><?php echo $this->escapeHtml($category->getDescription()); ?> (<?php echo $this->escapeHtml($category->getCode()); ?>)
    </option>
    <?php
    echo $this->partial('application/category/partial/category_option.phtml', array(
        'categories' => $category->getChildren(),
        'level' => ($level + 1),
        'numberSelected' => $numberSelected
    ));
    ?>
<?php endforeach; ?>