<?php foreach ($categories as $category): ?><?php /* @var $category \Application\Model\Entity\Category */ ?>
    <tr <?php if ($category->getParent() !== null): ?>
            meta-parent="<?php echo $this->escapeHtml($category->getParent()->getNumber()); ?>"
        <? endif; ?>
        meta-number="<?php echo $this->escapeHtml($category->getNumber()); ?>">
        <td>
            <?php echo str_repeat('&nbsp;', $level * 3); ?>
            <input type="radio" name="code" id="code" value="<?php echo $this->escapeHtml($category->getNumber()); ?>" />
            <?php echo $this->escapeHtml($category->getCode()); ?>
        </td>
        <td><?php echo $this->escapeHtml($category->getDescription()); ?></td>
        <td><?php echo $this->escapeHtml($this->translate($category->getFlowType() ? "Input" : "Output")); ?></td>
    </tr>
    <?php echo $this->partial('application/category/partial/category_tr.phtml', array('categories' => $category->getChildren(), 'level' => ($level + 1))); ?>
<?php endforeach; ?>