<ul class="nav">
    <?php $count = 0 ?>
    <?php foreach ($this->container as $page): ?>
        <li>
            <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
            <?php // when using partials we need to manually check for ACL conditions ?>
            <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
            <?php if (!$page->hasPages()): ?>
                <a class="nav-header" href="<?php echo $page->getHref() ?>"><?php echo $this->translate($page->getLabel()) ?></a>
            <?php else: ?>
                <a class="dropdown-toggle" data-toggle="dropdown"><span><?php echo $this->translate($page->getLabel()) ?></span></a>
                <ul class="dropdown-menu" id="page_<?php echo $count ?>">
                    <?php foreach ($page->getPages() as $child): ?>
                        <?php if (!$child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                        <li><a href="<?php echo $child->getHref() ?>"><?php echo $this->translate($child->getLabel()) ?></a></li>
                    <?php endforeach ?>
                </ul>
            <?php endif ?>
        </li>
    <?php endforeach ?>
</ul>