<?php if ($this->pageCount): ?>
    <span class="pagination">
        <ul>
            <?php /*  Previous page link */ ?>
            <li>
                <a <?php if (isset($this->previous)): ?> href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>" <?php endif; ?>>
                    <?php echo $this->escapeHtml('«'); ?>
                </a>
            </li>
            <?php /*  Numbered page links */ ?>
            <?php foreach ($this->pagesInRange as $page): ?>
                <li>
                    <?php if ($page != $this->current): ?>
                        <a href="<?php echo $this->url($this->route, array('page' => $page)); ?>"><?php echo $page; ?></a>
                    <?php else: ?>
                        <a><?php echo $page; ?></a>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
            <?php /* Next page link */ ?>
            <li>
                <?php if (isset($this->next)): ?>
                    <a href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>"><?php echo $this->escapeHtml('»'); ?></a>
                <?php else: ?>
                    <a><?php echo $this->escapeHtml('»'); ?></a>
                <?php endif; ?>
            </li>
        </ul>
    </span>
<?php endif; ?>