<?php if ($this->pageCount): ?>
    <span class="pagination">
        <ul>
            <?php /*  Previous page link */ ?>
            <?php if (isset($this->previous)): ?>             
                <li><a href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>" ><?php echo $this->escapeHtml('«'); ?></a></li>
            <?php else: ?>
                <li class="disabled"><a><?php echo $this->escapeHtml('«'); ?></a></li>
            <?php endif; ?>

            <?php /*  Numbered page links */ ?>
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li><a href="<?php echo $this->url($this->route, array('page' => $page)); ?>"><?php echo $page; ?></a></li>
                <?php else: ?>
                    <li class="active"><a><?php echo $page; ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php /* Next page link */ ?>
            <?php if (isset($this->next)): ?>
                <li><a href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>"><?php echo $this->escapeHtml('»'); ?></a></li>
            <?php else: ?>
                <li class="disabled"><a><?php echo $this->escapeHtml('»'); ?></a></li>
            <?php endif; ?>
        </ul>
    </span>
<?php endif; ?>