<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->

<?php if ($this->pageCount): ?>
    <div class="pagination">
        <ul>
            <!-- Previous page link -->

            <li>
                <a <?php if (isset($this->previous)): ?> href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>" <?php endif; ?>>
                    <?php echo $this->escapeHtml('«'); ?>
                </a>
            </li>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li><a href="<?php echo $this->url($this->route, array('page' => $page)); ?>"><?php echo $page; ?></a></li>
                <?php else: ?>
                    <li><a><?php echo $page; ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li>
                <a <?php if (isset($this->next)): ?> href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>"<?php endif; ?>>
                    <?php echo $this->escapeHtml('»'); ?>
                </a>
            </li>
        </ul>
    </div>
<?php endif; ?>