<?php $this->placeholder('content')->captureStart(); ?>
<?php /* @var $form \Admin\Form\User\Remove */ ?>
<?php $form->setAttribute('action', $this->url('category', array('action' => 'remove', 'number' => $form->get('number')->getValue()))); ?>
<div class="well well-message">
    <?php echo $this->form()->openTag($form); ?>
    <h4>
        <?php
        echo $this->escapeHtml(sprintf($this->translate('You really want to remove category %s (%s) (and children)?'), $form->get('description')->getValue(), $form->get('code')->getValue()));
        ?>
    </h4>
        <?php echo $this->formHidden($form->get('number')); ?>
    <div class="form-actions">
    <?php echo $this->ztbFormButton($form->get('submitAction')->setAttribute('class', 'input-medium'), null, array('btn_type' => 'danger')); ?>
        <a class="btn pull-right input-medium" href="<?php echo $form->get('cancel')->getAttribute('formaction'); ?>">
        <?php echo $this->escapeHtml($this->translate($form->get('cancel')->getLabel())); ?>
        </a>
    </div>
<?php echo $this->form()->closeTag($form); ?>
</div>
    <?php $this->placeholder('content')->captureEnd(); ?>
<?php echo $this->stripContent($this->placeholder('content')); ?>
