<?php $this->placeholder('content')->captureStart(); ?>
<?php
/* @var $form \Admin\Form\User\User */
/* @var $action string */

$form->setAttribute('class', 'form-horizontal');
if ($action == 'update'):
    $form->get('dateCreation')->setAttribute('readonly', 'readonly');
    $form->get('active')->setAttribute('disabled', 'disabled');
    if ($this->auth('role') != 'admin'):
        $form->get('role')->setAttribute('disabled', 'disabled');
    endif;
    $form->setAttribute('action', $this->url('user', array('action' => 'update', 'id' => $form->get('id')->getValue())));
else:
    $form->readonly();
endif;
foreach ($form as $element):
    $element->setLabelAttributes(array('class' => 'control-label'));

    if (($element instanceof \Zend\Form\Element\Button)) :
        $element->setAttribute('class', 'btn');
    endif;
endforeach;
?>
<div class="well">
    <h3 class="entity-title">
        <?php if ($this->auth('role') === 'admin'): ?>
            <div class="btn-group">
                <a class="btn btn-primary" title="<?php echo $this->escapeHtml($this->translate('List users')) ?>"  href="<?php echo $this->url('user', array('action' => 'index')); ?>"><span class="icon icon-th-list icon-white"></span></a>
                <?php if ($action != 'detail'): ?>
                    <a class="btn btn-info" title="<?php echo $this->escapeHtml($this->translate('Detail user')) ?>" href="<?php echo $this->url('user', array('action' => 'detail', 'id' => $form->get('id')->getValue())); ?>"><span class="icon icon-book icon-white"></span></a>
                <?php endif; ?>
                <?php if ($action != 'update'): ?>
                    <a class="btn btn-warning" title="<?php echo $this->escapeHtml($this->translate('Alter user')) ?>" href="<?php echo $this->url('user', array('action' => 'update', 'id' => $form->get('id')->getValue())); ?>"><span class="icon icon-edit icon-white"></span></a>
                <?php endif; ?>
                <a class="btn btn-danger" title="<?php echo $this->escapeHtml($this->translate('Remove user')) ?>" href="<?php echo $this->url('user', array('action' => 'remove', 'id' => $form->get('id')->getValue())); ?>"><span class="icon icon-remove icon-white"></span></a>
            </div>
        <?php endif; ?>
        <?php echo $this->escapeHtml($this->translate("User") . ": {$form->get('name')->getValue()}"); ?>
    </h3>

    <?php if ($action == 'update'): ?>
        <?php if (count($form->getExceptionMessages()) > 0): ?>
            <div class="alert alert-error">
                <b><?php echo $this->escapeHtml($this->translate("Exceptions")); ?>:</b><br/>
                <ul class="alert-block alert-warning">
                    <?php foreach ($form->getExceptionMessages() as $message): ?>
                        <li><?php echo $this->escapeHtml($message); ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
        <?php foreach ($form->getMessages() as $key => $messages): ?>
            <div class="alert alert-error">
                <b><?php echo $this->escapeHtml($this->translate($form->get($key)->getLabel())); ?>:</b><br/>
                <ul class="alert-block alert-warning">
                    <?php foreach ($messages as $message): ?>
                        <li><?php echo $this->escapeHtml($message); ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php echo $this->form()->openTag($form); ?>
    <?php echo $this->formHidden((new \Zend\Form\Element\Hidden('returnTo'))->setValue($this->url('user', array('action' => $action, 'id' => $form->get('id')->getValue())))); ?>
    <?php echo $this->formHidden($form->get('id')); ?>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('name')); ?>
        <div class="controls">
            <?php echo $this->formInput($form->get('name')->setAttribute('class', 'input-xxlarge')); ?>
        </div>
    </div>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('email')); ?>
        <div class="controls">
            <?php echo $this->formInput($form->get('email')->setAttribute('class', 'input-xlarge')); ?>
        </div>
    </div>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('username')); ?>
        <div class="controls">
            <?php echo $this->formInput($form->get('username')); ?>
        </div>
    </div>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('role')); ?>
        <div class="controls">
            <?php echo $this->formSelect($form->get('role')); ?>
        </div>
    </div>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('active')); ?>
        <div class="controls">
            <?php if ($form->get('active')->getValue()): ?>
                <button class="btn btn-inverse input-medium" title="<?php echo $this->escapeHtml($this->translate('Lock user')) ?>" formaction="<?php echo $this->url('user', array('action' => 'lock', 'id' => $form->get('id')->getValue())); ?>"><span class="icon icon-eye-close icon-white"></span> <?php echo $this->escapeHtml($this->translate('Lock user')) ?></button>
            <?php else: ?>
                <button class="btn btn-success input-medium" title="<?php echo $this->escapeHtml($this->translate('Unlock user')) ?>" formaction="<?php echo $this->url('user', array('action' => 'unlock', 'id' => $form->get('id')->getValue())); ?>"><span class="icon icon-eye-open icon-white"></span> <?php echo $this->escapeHtml($this->translate('Unlock user')) ?></button>
            <?php endif; ?>
        </div>
    </div>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('dateCreation')); ?>
        <div class="controls">
            <?php echo $this->formInput($form->get('dateCreation')); ?>
        </div>
    </div>
    <?php if ($action == 'update'): ?>
        <div class="form-actions">
            <?php echo $this->formButton()->render($form->get('submit')->setAttribute('class', 'btn btn-primary input-large'), 'Update'); ?>
            <?php echo $this->formButton()->render($form->get('cancel')->setAttribute('class', 'btn btn-inverse input-large')->setAttribute('formaction', $this->url('userList')), 'Cancel'); ?>
            <button class="btn btn-warning input-large" title="<?php echo $this->escapeHtml($this->translate('Alter password')) ?>" formaction="<?php echo $this->url('user', array('action' => 'alterPassword', 'id' => $form->get('id')->getValue())); ?>"><span class="icon icon-lock icon-white float-left"></span> <?php echo $this->escapeHtml($this->translate('Alter password')) ?></button>
        </div>
    <?php endif; ?>
    <?php echo $this->form()->closeTag($form); ?>
</div>
<?php $this->placeholder('content')->captureEnd(); ?>
<?php echo $this->stripContent($this->placeholder('content')); ?>