<?php $this->placeholder('content')->captureStart(); ?>
<?php
/* @var $form \Admin\Form\User\User */
/* @var $action string */

if ($action == 'update' || $action == 'updateProfile' || $action == 'create'):
    $form->get('dateCreation')->setAttribute('readonly', 'readonly');
    if ($action == 'update'):
        $form->get('role')->setAttribute('disabled', 'disabled');
    endif;

    if ($action === 'create'):
        $form->setAttribute('action', $this->url('user', array('action' => 'create')));
        $form->get('submitAction')->setLabel('Create');
    else:
        $form->get('active')->setAttribute('disabled', 'disabled');

        if ($action === 'update'):
            $form->setAttribute('action', $this->url('user', array('action' => 'update', 'id' => $form->get('id')->getValue())));
        else:
            $form->setAttribute('action', $this->url('user', array('action' => 'updateProfile')));
        endif;

        $form->get('submitAction')->setLabel('Update');
    endif;
else:
    $form->readonly();
endif;
?>
<div class="well">
    <?php echo $this->form()->openTag($this->ztbFormPrepare($form, 'horizontal')); // <form %s>  ?>
    <?php echo $this->formHidden((new \Zend\Form\Element\Hidden('returnTo'))->setValue($this->url('user', array('action' => $action, 'id' => $form->get('id')->getValue())))); ?>
    <?php echo $this->formHidden($form->get('id')); ?>

    <h3 class="entity-title">
        <?php if ($action == 'update' || $action == 'detail'): ?>
            <div class="btn-group pull-right">
                <button class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                    <span class="icon icon-wrench icon-white"></span> 
                    <?php echo $this->escapeHtml($this->translate('Options')) ?> <i class="caret"></i>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        <a href="<?php echo $this->url('user', array('action' => 'index')); ?>">
                            <span class="icon icon-th-list"></span>
                            <?php echo $this->escapeHtml($this->translate('List all users')); ?>
                        </a>
                    </li>
                    <?php if ($action != 'detail'): ?>
                        <li>
                            <a href="<?php echo $this->url('user', array('action' => 'detail', 'id' => $form->get('id')->getValue())); ?>">
                                <span class="icon icon-book"></span>
                                <?php echo $this->escapeHtml($this->translate('Detail user')); ?>
                            </a>
                        </li>
                    <?php endif; ?>
                    <?php if ($action != 'update'): ?>
                        <li>
                            <?php
                            echo $this->ztbFormButton((new \Zend\Form\Element\Button('updateUser_' . time()))->setAttributes(
                                            array(
                                                'type' => 'submit',
                                                'formaction' => $this->url('user', array('action' => 'update'))
                                    )), 'Alter user', array('icon' => 'edit', 'btn_type' => 'link',));
                            ?>
                        </li>
                    <?php endif; ?>
                    <li>
                        <?php
                        echo $this->ztbFormButton((new \Zend\Form\Element\Button('resetPassword_' . time()))->setAttributes(array(
                                    'class' => 'input-large',
                                    'type' => 'submit',
                                    'formaction' => $this->url('user', array('action' => 'resetPassword')),
                                )), 'Reset Password', array('icon' => 'lock', 'btn_type' => 'link'));
                        ?>
                    </li>
                    <li>
                        <?php
                        echo $this->ztbFormButton((new \Zend\Form\Element\Button('removeUser_' . time()))->setAttributes(
                                        array(
                                            'type' => 'submit',
                                            'formaction' => $this->url('user', array('action' => 'remove', 'id' => $form->get('id')->getValue()))
                                )), 'Remove user', array('icon' => 'remove', 'btn_type' => 'link',));
                        ?>
                    </li>

                </ul>
            </div><!-- /btn-group -->

            <div class="btn-group">
            </div>
        <?php elseif ($action == 'detailProfile'): ?>
            <?php
            echo $this->ztbFormButton((new \Zend\Form\Element\Button('editProfile_' . time()))->setAttributes(
                            array(
                                'type' => 'submit',
                                'class' => 'pull-right',
                                'formaction' => $this->url('user', array('action' => 'updateProfile'))
                    )), 'Edit Profile', array('icon' => 'edit white', 'btn_type' => 'warning',));
            ?>
        <?php endif; ?>
        <?php
        if ($action == 'detail'):
            echo $this->escapeHtml($this->translate("User Details"));
        elseif ($action == 'create'):
            echo $this->escapeHtml($this->translate("Create User"));
        elseif ($action == 'update'):
            echo $this->escapeHtml($this->translate("Edit User"));
        elseif ($action == 'detailProfile'):
            echo $this->escapeHtml($this->translate("Profile Details"));
        elseif ($action == 'updateProfile'):
            echo $this->escapeHtml($this->translate("Edit Profile"));
        endif;
        ?>
    </h3>

    <?php if ($action == 'updateProfile' || $action == 'update' || $action == 'create'): ?>
        <?php if (count($form->getExceptionMessages()) > 0): ?>
            <div class="alert alert-error">
                <b><?php echo $this->escapeHtml($this->translate("Exceptions")); ?>:</b><br/>
                <ul class="alert-block alert-warning">
                    <?php foreach ($form->getExceptionMessages() as $message): ?>
                        <li><?php echo $this->escapeHtml($message); ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
        <?php foreach ($form->getMessages() as $key => $messages): ?>
            <div class="alert alert-error">
                <b><?php echo $this->escapeHtml($this->translate($form->get($key)->getLabel())); ?>:</b><br/>
                <ul class="alert-block alert-warning">
                    <?php foreach ($messages as $message): ?>
                        <li><?php echo $this->escapeHtml($message); ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('name')); ?>
        <div class="controls">
            <?php echo $this->formInput($form->get('name')->setAttribute('class', 'input-xxlarge')); ?>
        </div>
    </div>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('email')); ?>
        <div class="controls">
            <?php echo $this->formInput($form->get('email')->setAttribute('class', 'input-xlarge')); ?>
        </div>
    </div>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('username')); ?>
        <div class="controls">
            <?php echo $this->formInput($form->get('username')); ?>
        </div>
    </div>
    <?php if ($action == 'detailProfile' || $action == 'detail' || $action == 'update' || $action == 'create'): ?>
        <div class="control-group">
            <?php echo $this->formLabel($form->get('role')); ?>
            <div class="controls">
                <?php echo $this->formSelect($form->get('role')); ?>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($action == 'detail' || $action == 'update'): ?>
        <div class="control-group">
            <?php echo $this->formLabel($form->get('active')); ?>
            <div class="controls">
                <?php if ($form->get('active')->getValue()): ?>
                    <button class="btn btn-inverse" title="<?php echo $this->escapeHtml($this->translate('Lock user')) ?>" formaction="<?php echo $this->url('user', array('action' => 'lock', 'id' => $form->get('id')->getValue())); ?>"><span class="icon icon-eye-close icon-white"></span> <?php echo $this->escapeHtml($this->translate('Lock user')) ?></button>
                <?php else: ?>
                    <button class="btn btn-success" title="<?php echo $this->escapeHtml($this->translate('Unlock user')) ?>" formaction="<?php echo $this->url('user', array('action' => 'unlock', 'id' => $form->get('id')->getValue())); ?>"><span class="icon icon-eye-open icon-white"></span> <?php echo $this->escapeHtml($this->translate('Unlock user')) ?></button>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('dateCreation')); ?>
        <div class="controls">
            <?php echo $this->formInput($form->get('dateCreation')); ?>
        </div>
    </div>
    <?php if ($action == 'update' || $action == 'updateProfile' || $action == 'create'): ?>
        <div class="form-actions">
            <?php echo $this->ztbFormButton($form->get('submitAction')->setAttribute('class', 'input-medium'), null, array('btn_type' => 'warning')); ?>
            &nbsp;
            <?php echo $this->ztbFormButton($form->get('cancel')->setAttribute('class', 'input-medium')); ?>
            &nbsp;
            <?php if ($action == 'updateProfile'): ?>
                <?php
                echo $this->ztbFormButton($form->get('changePassword')->setAttributes(array(
                            'class' => 'input-large',
                            'type' => 'submit',
                            'formaction' => $this->url('user', array('action' => 'changePassword')),
                        )), null, array('icon' => 'lock'));
                ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>
    <?php echo $this->form()->closeTag($form); // </form>  ?>
</div>
<?php $this->placeholder('content')->captureEnd(); ?>
<?php //echo ($this->placeholder('content'));   ?>
<?php echo $this->stripContent($this->placeholder('content')); ?>