<?php $this->placeholder('content')->captureStart(); ?>
<?php /* @var $form \Admin\Form\User\ChangePassword */ ?>
<?php /* @var $action string */ ?>
<?php $form->setAttribute('class', 'form-vertical'); ?>
<div class="well well-message">
    <?php $this->form()->openTag($form); ?>
    <?php echo $this->formHidden((new \Zend\Form\Element\Hidden('returnTo'))->setValue($this->url('user', array('action' => $action, 'id' => $form->get('id')->getValue())))); ?>
    <?php echo $this->formHidden($form->get('id')); ?>
    <h3>
        <?php echo $this->escapeHtml($this->translate("Change Password")); ?>
    </h3>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('oldPassword')); ?>
        <div class="controls">
            <?php echo $this->formInput($form->get('oldPassword')->setAttribute('class', 'input-xlarge')); ?>
        </div>
    </div>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('newPassword')); ?>
        <div class="controls">
            <?php echo $this->formInput($form->get('newPassword')->setAttribute('class', 'input-xlarge')); ?>
        </div>
    </div>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('confirmPassword')); ?>
        <div class="controls">
            <?php echo $this->formInput($form->get('confirmPassword')->setAttribute('class', 'input-xlarge')); ?>
        </div>
    </div>

    <?php $this->form()->closeTag(); ?>
</div>
<?php $this->placeholder('content')->captureEnd(); ?>
<?php echo $this->stripContent($this->placeholder('content')); ?>

