<?php $this->placeholder('content')->captureStart(); ?>
<?php /* @var $form \Admin\Form\User\ChangePassword */ ?>
<?php /* @var $action string */ ?>
<?php $form->setAttribute('action', $this->url('user', array('action' => 'changePassword'))); ?>
<div class="well well-message">
    <?php if ($action === 'change'): ?>
        <?php echo $this->form()->openTag($this->ztbFormPrepare($form, 'horizontal')); ?>
    <?php else: ?>    
        <?php echo $this->form()->openTag($this->ztbFormPrepare($form)); ?>
    <?php endif; ?>

    <?php echo $this->formHidden((new \Zend\Form\Element\Hidden('returnTo'))->setValue($this->url('user', array('action' => 'detail', 'id' => $form->get('id')->getValue())))); ?>
    <?php echo $this->formHidden($form->get('id')); ?>
    <?php if ($action === 'change'): ?>
        <h3 class="entity-title"><?php echo $this->escapeHtml($this->translate("Change Password")); ?></h3>
        <div class="control-group">
            <?php echo $this->formLabel($form->get('oldPassword')); ?>
            <div class="controls">
                <?php echo $this->formInput($form->get('oldPassword')->setAttribute('class', 'input-xlarge')); ?>
            </div>
        </div>
        <div class="control-group">
            <?php echo $this->formLabel($form->get('newPassword')); ?>
            <div class="controls">
                <?php echo $this->formInput($form->get('newPassword')->setAttribute('class', 'input-xlarge')); ?>
            </div>
        </div>
        <div class="control-group">
            <?php echo $this->formLabel($form->get('confirmPassword')); ?>
            <div class="controls">
                <?php echo $this->formInput($form->get('confirmPassword')->setAttribute('class', 'input-xlarge')); ?>
            </div>
        </div>
        <div class="form-actions">
            <?php echo $this->ztbFormButton($form->get('changePassword'), null, array('btn_type' => 'warning')); ?>
            &nbsp;
            <?php echo $this->ztbFormButton($form->get('cancel')->setAttribute('class', 'input-small')); ?>
            &nbsp;
        </div>
    <?php else: ?>
        <h4><?php echo $this->escapeHtml(sprintf($this->translate("Reset password of %s (%s)?"), $user->getName(), $user->getUsername())); ?></h4>
        <div class="form-actions">
            <?php echo $this->ztbFormButton($form->get('changePassword'), null, array('btn_type' => 'warning')); ?>
            &nbsp;
            <?php echo $this->ztbFormButton($form->get('cancel')->setAttribute('class', 'pull-right input-medium')); ?>
            &nbsp;
        </div>
    <?php endif; ?>

    <?php $this->form()->closeTag(); ?>
</div>
<?php $this->placeholder('content')->captureEnd(); ?>
<?php echo $this->stripContent($this->placeholder('content')); ?>

