<?php $this->placeholder('content')->captureStart(); ?>
<?php
/* @var $form \Application\Form\Moviment\MovimentForm */
/* @var $action string */

$caption = "Moviment";
if ($action == 'update' || $action == 'create'):
    if ($action === 'create'):
        $caption = "Create Moviment";
        $form->setAttribute('action', $this->url('moviment', array('action' => 'create')));
    else:
        $caption = "Create Category";
        $form->setAttribute('action', $this->url('moviment', array('action' => 'update', 'id' => $form->get('id')->getValue())));
    endif;

    if (!$form->get('cancel')->getAttribute('formaction')):
        $form->get('cancel')->setAttribute('formaction', $this->url('movimentList'));
    endif;
else:
    $caption = "Moviment Details";
    $form->readonly();
endif;
?>
<div class="well">
    <?php echo $this->form()->openTag($this->ztbFormPrepare($form, 'horizontal')); // <form %s>    ?>
    <?php if ($action !== 'create'): ?>
        <?php echo $this->formHidden((new \Zend\Form\Element\Hidden('returnTo'))->setValue($this->url('moviment', array('action' => $action, 'id' => $form->get('id')->getValue())))); ?>
        <?php echo $this->formHidden($form->get('id')); ?>
    <?php endif; ?>
    <h3 class="entity-title">
        <?php if ($action == 'update' || $action == 'detail'): ?>
            <div class="btn-group pull-right">
                <button class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                    <span class="icon icon-wrench icon-white"></span> 
                    <?php echo $this->escapeHtml($this->translate('Options')) ?> <i class="caret"></i>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        <a href="<?php echo $this->url('moviment', array('action' => 'index')); ?>">
                            <span class="icon icon-th-list"></span>
                            <?php echo $this->escapeHtml($this->translate('List moviments')); ?>
                        </a>
                    </li>
                    <?php if ($action !== 'detail'): ?>
                        <li>
                            <?php echo $this->ztbFormButton($form->get('detailButton'), null, array('icon' => 'book', 'btn_type' => 'link')); ?>
                        </li>
                    <?php endif; ?>
                    <?php if ($action !== 'update'): ?>
                        <li><?php echo $this->ztbFormButton($form->get('editButton'), null, array('icon' => 'edit', 'btn_type' => 'link')); ?>
                        </li>
                    <?php endif; ?>
                    <li>                
                        <?php echo $this->ztbFormButton($form->get('removeButton'), null, array('icon' => 'remove', 'btn_type' => 'link')); ?>
                    </li>
                </ul>
            </div>
        <?php endif; ?>
        <?php echo $this->escapeHtml($this->translate($caption)); ?>
    </h3>

    <?php if ($action == 'update' || $action == 'create'): ?>
        <?php if (count($form->getExceptionMessages()) > 0): ?>
            <div class="alert alert-error">
                <b><?php echo $this->escapeHtml($this->translate("Exceptions")); ?>:</b><br/>
                <ul class="alert-block alert-warning">
                    <?php foreach ($form->getExceptionMessages() as $message): ?>
                        <li><?php echo $this->escapeHtml($message); ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
        <?php foreach ($form->getMessages() as $key => $messages): ?>
            <div class="alert alert-error">
                <b><?php echo $this->escapeHtml($this->translate($form->get($key)->getLabel())); ?>:</b><br/>
                <ul class="alert-block alert-warning">
                    <?php foreach ($messages as $message): ?>
                        <li><?php echo $this->escapeHtml($message); ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <div class="control-group">
        <?php if ($action === 'update' || $action === 'create'): ?>
            <?php echo $this->formLabel($form->get('category')); ?>
            <div class="controls">
                <?php echo $this->formSelect()->openTag($form->get('category')); ?>
                <?php
                echo $this->partial('application/category/partial/category_option.phtml', array(
                    'categories' => $categories,
                    'level' => 0,
                    'numberSelected' => $form->get('category')->getValue(),
                    'none' => false,
                ));
                ?>
                <?php echo $this->formSelect()->closeTag(); ?>
            </div>
        <?php else: ?>
            <?php echo $this->formLabel($form->get('category_number')); ?>
            <div class="controls">
                <?php echo $this->formHidden($form->get('category_number')); ?>
                <?php echo $this->formInput($form->get('category_code')->setAttribute('class', 'input-small')); ?>
                &nbsp;
                <?php echo $this->ztbFormButton($form->get('categoryDetailButton')->setAttribute('formaction', $this->url('category', array('action' => 'detail', 'number' => $form->get('category_number')->getValue()))), " ", array('icon' => 'book')); ?>
                &nbsp;
                <?php echo $this->formInput($form->get('category_description')); ?>
            </div>
        <?php endif; ?>
    </div>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('dateEmission')); ?>
        <div class="controls">
            <?php echo $this->formDate($form->get('dateEmission')); ?>
        </div>
    </div>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('value')); ?>
        <div class="controls">
            <?php echo $this->formNumber($form->get('value')); ?>
        </div>
    </div>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('description')); ?>
        <div class="controls">
            <?php echo $this->formInput($form->get('description')->setAttribute('class', 'input-xxlarge')); ?>
        </div>
    </div>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('notes')); ?>
        <div class="controls">
            <?php echo $this->formTextArea($form->get('notes')->setAttribute('class', 'input-xxlarge')); ?>
        </div>
    </div>
    <?php if ($action == 'update' || $action == 'create'): ?>
        <div class="form-actions">
            <?php echo $this->ztbFormButton($form->get('submitAction')->setAttribute('class', 'input-medium'), null, array('btn_type' => 'warning')); ?>
            &nbsp;
            <a href="<?php echo $form->get('cancel')->getAttribute('formaction'); ?>" class="btn input-medium">
                <?php echo $this->escapeHtml($this->translate($form->get('cancel')->getLabel())); ?>
            </a>
        </div>
    <?php endif; ?>
    <?php echo $this->form()->closeTag(); ?>
</div>
<?php $this->placeholder('content')->captureEnd(); ?>
<?php echo $this->stripContent($this->placeholder('content')); ?>